import { useEffect, useMemo, useState } from 'react';
import { Archive, ArrowLeft, CheckCircle2, ChevronDown, ChevronUp, GraduationCap, Info, MoreVertical, Pencil, Plus, Search, UserPlus, UserRound, Users, X } from 'lucide-react';
import { Link } from 'react-router-dom';

const storageKey = 'scholanode-academic-classes';
const staff = ['Aisha Ibrahim', 'Abdulrahman Musa', 'Fatima Yusuf', 'Sani Bello', 'Maryam Umar', 'Ibrahim Abdullahi'];
const starterClasses = [
  ['JSS 1', 'A', 42, 'Aisha Ibrahim'], ['JSS 1', 'B', 39, 'Abdulrahman Musa'], ['JSS 2', 'A', 45, ''], ['JSS 2', 'B', 41, 'Fatima Yusuf'], ['SS 1', 'Science', 31, ''], ['SS 1', 'Arts', 27, 'Sani Bello'], ['SS 1', 'Commercial', 29, 'Maryam Umar'],
].map(([classLevel, arm, studentCount, formMaster], index) => ({ id: String(index + 1), classLevel, arm, studentCount, formMaster }));

export default function Classes() {
  const [classes, setClasses] = useState(() => loadClasses());
  const [search, setSearch] = useState('');
  const [expanded, setExpanded] = useState(() => ['JSS 1', 'JSS 2', 'SS 1']);
  const [modal, setModal] = useState(null);
  const [menu, setMenu] = useState(null);
  const [form, setForm] = useState({ classLevel: '', arm: '', studentCount: '' });

  useEffect(() => localStorage.setItem(storageKey, JSON.stringify(classes)), [classes]);

  const grouped = useMemo(() => {
    const query = search.trim().toLowerCase();
    return Object.entries(classes.reduce((groups, item) => { (groups[item.classLevel] ||= []).push(item); return groups; }, {})).map(([level, items]) => [level, items.filter((item) => !query || `${item.classLevel} ${item.arm} ${item.formMaster}`.toLowerCase().includes(query))]).filter(([, items]) => items.length);
  }, [classes, search]);
  const totalStudents = classes.reduce((total, item) => total + Number(item.studentCount || 0), 0);
  const assigned = classes.filter((item) => item.formMaster).length;

  const openCreate = () => { setForm({ classLevel: '', arm: '', studentCount: '' }); setModal({ type: 'create' }); };
  const openEdit = (item) => { setForm({ classLevel: item.classLevel, arm: item.arm, studentCount: item.studentCount }); setModal({ type: 'edit', item }); setMenu(null); };
  const saveClass = (event) => { event.preventDefault(); const classLevel = form.classLevel.trim(); const arm = form.arm.trim(); if (!classLevel || !arm) return; if (modal.type === 'edit') setClasses((current) => current.map((item) => item.id === modal.item.id ? { ...item, classLevel, arm, studentCount: Number(form.studentCount) || 0 } : item)); else setClasses((current) => [...current, { id: crypto.randomUUID(), classLevel, arm, studentCount: Number(form.studentCount) || 0, formMaster: '' }]); setModal(null); };
  const archiveClass = (id) => { setClasses((current) => current.filter((item) => item.id !== id)); setMenu(null); };
  const assign = (id, formMaster) => { setClasses((current) => current.map((item) => item.id === id ? { ...item, formMaster } : item)); setModal(null); };

  return <main className="min-h-screen bg-slate-50 px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="mx-auto max-w-7xl"><Link to="/academic-setup" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-[#071A52]"><ArrowLeft size={17} /> Back to academic setup</Link><section className="relative mt-5 overflow-hidden rounded-3xl bg-linear-to-br from-[#071A52] via-[#0A2463] to-[#123A8F] p-6 text-white shadow-2xl sm:p-9"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full border-36 border-cyan-300/10" /><div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm font-medium"><GraduationCap size={17} /> Academic management</div><p className="text-xs font-bold uppercase tracking-[0.18em] text-cyan-200">School structure</p><h1 className="mt-3 text-3xl font-extrabold leading-tight sm:text-4xl">Classes & arms</h1><p className="mt-3 max-w-2xl text-base leading-7 text-blue-100">Organize your class levels, arms and form masters in one clear workspace.</p></div><button type="button" onClick={openCreate} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-cyan-400 px-5 py-3 font-bold text-[#071A52] hover:bg-cyan-300"><Plus size={18} /> Create class</button></div></section>

    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Summary label="Total classes" value={classes.length} icon={GraduationCap} /><Summary label="Students" value={totalStudents} icon={Users} /><Summary label="Form masters" value={`${assigned}/${classes.length}`} icon={UserRound} highlight={assigned === classes.length && classes.length > 0} /><Summary label="Class levels" value={new Set(classes.map((item) => item.classLevel)).size} icon={CheckCircle2} /></div>
    {classes.some((item) => !item.formMaster) && <div className="mt-6 flex items-start gap-3 rounded-2xl border border-amber-100 bg-amber-50 p-4 text-amber-900"><Info size={19} className="mt-0.5 shrink-0 text-amber-600" /><div><p className="text-sm font-bold">Some classes need a form master</p><p className="mt-1 text-sm leading-6 text-amber-800">Assign a form master to make class ownership clear for your school team.</p></div></div>}
    <div className="mt-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-cyan-600">Class directory</p><h2 className="mt-1 text-2xl font-extrabold text-[#071A52]">Your class levels</h2></div><div className="relative w-full sm:w-80"><Search size={18} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search class, arm or form master" className="w-full rounded-2xl border border-slate-200 bg-white py-3 pl-10 pr-4 text-sm outline-none focus:border-cyan-500 focus:ring-4 focus:ring-cyan-500/10" /></div></div>
    <section className="mt-5 space-y-4">{grouped.map(([level, items]) => { const isExpanded = expanded.includes(level); return <article key={level} className="overflow-visible rounded-3xl border border-slate-200 bg-white shadow-sm"><button type="button" onClick={() => setExpanded((current) => current.includes(level) ? current.filter((item) => item !== level) : [...current, level])} className="flex w-full items-center justify-between gap-4 p-5 text-left hover:bg-slate-50 sm:p-6"><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-sky-50 text-[#071A52]"><GraduationCap size={23} /></span><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl font-extrabold text-[#071A52]">{level}</h3><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-500">{items.length} arms</span></div><p className="mt-1 text-sm text-slate-500">{items.reduce((total, item) => total + Number(item.studentCount || 0), 0)} students across this level</p></div></div>{isExpanded ? <ChevronUp className="text-slate-400" /> : <ChevronDown className="text-slate-400" />}</button>{isExpanded && <div className="grid gap-4 border-t border-slate-100 bg-slate-50/70 p-4 sm:p-6 lg:grid-cols-2">{items.map((item) => <ClassCard key={item.id} item={item} menu={menu === item.id} onMenu={() => setMenu((current) => current === item.id ? null : item.id)} onEdit={() => openEdit(item)} onArchive={() => archiveClass(item.id)} onAssign={() => setModal({ type: 'assign', item })} />)}</div>}</article>; })}</section>
    {grouped.length === 0 && <EmptyState search={search} onCreate={openCreate} />}
  </div>{modal && <ClassModal modal={modal} form={form} setForm={setForm} onClose={() => setModal(null)} onSave={saveClass} onAssign={assign} />}</main>;
}

function ClassCard({ item, menu, onMenu, onEdit, onArchive, onAssign }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-cyan-200 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#071A52] text-sm font-extrabold text-white">{item.arm.slice(0, 3)}</span><div><h4 className="text-lg font-extrabold text-[#071A52]">{item.classLevel} <span className="text-slate-400">·</span> {item.arm}</h4><p className="mt-1 flex items-center gap-1.5 text-sm text-slate-500"><Users size={15} /> {item.studentCount || 0} students</p></div></div><div className="relative"><button type="button" onClick={onMenu} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100 hover:text-[#071A52]"><MoreVertical size={18} /></button>{menu && <div className="absolute right-0 top-10 z-20 w-44 rounded-2xl border border-slate-200 bg-white p-1.5 shadow-xl"><button type="button" onClick={onEdit} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold text-slate-700 hover:bg-slate-50"><Pencil size={16} /> Edit class</button><button type="button" onClick={onArchive} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold text-red-600 hover:bg-red-50"><Archive size={16} /> Archive class</button></div>}</div></div><div className="mt-5 flex items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Form master</p>{item.formMaster ? <p className="mt-1 flex items-center gap-2 text-sm font-bold text-slate-700"><UserRound size={15} className="text-emerald-600" /> {item.formMaster}</p> : <p className="mt-1 text-sm font-semibold text-amber-700">Not assigned</p>}</div><button type="button" onClick={onAssign} className={`inline-flex items-center gap-1.5 rounded-xl px-3 py-2 text-xs font-bold ${item.formMaster ? 'border border-slate-200 bg-white text-slate-600' : 'bg-amber-500 text-white'}`}>{item.formMaster ? 'Change' : <><UserPlus size={14} /> Assign</>}</button></div></div>; }
function ClassModal({ modal, form, setForm, onClose, onSave, onAssign }) { const isAssign = modal.type === 'assign'; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#071A52]/40 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-cyan-600">Class management</p><h2 className="mt-1 text-2xl font-extrabold text-[#071A52]">{isAssign ? 'Assign form master' : modal.type === 'edit' ? 'Edit class' : 'Create class'}</h2><p className="mt-1 text-sm text-slate-500">{isAssign ? `${modal.item.classLevel} · ${modal.item.arm}` : 'Keep your class structure consistent.'}</p></div><button type="button" onClick={onClose} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100"><X size={19} /></button></div>{isAssign ? <div className="mt-7"><label className="mb-2 block text-sm font-bold text-slate-700">Form master</label><select defaultValue={modal.item.formMaster || ''} onChange={(event) => onAssign(modal.item.id, event.target.value)} className={inputClass}><option value="">Select staff member</option>{staff.map((member) => <option key={member} value={member}>{member}</option>)}</select></div> : <form onSubmit={onSave} className="mt-7 space-y-5"><Field label="Class level" value={form.classLevel} onChange={(value) => setForm((current) => ({ ...current, classLevel: value }))} placeholder="e.g. JSS 1" required /><Field label="Arm" value={form.arm} onChange={(value) => setForm((current) => ({ ...current, arm: value }))} placeholder="e.g. A, Science, Arts" required /><Field label="Student count" type="number" min="0" value={form.studentCount} onChange={(value) => setForm((current) => ({ ...current, studentCount: value }))} placeholder="0" /><ModalActions onClose={onClose} label={modal.type === 'edit' ? 'Save changes' : 'Create class'} /></form>}</div></div>; }
function Summary({ icon: Icon, label, value, highlight }) { return <div className={`rounded-3xl border bg-white p-5 shadow-sm ${highlight ? 'border-emerald-200' : 'border-slate-200'}`}><div className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${highlight ? 'bg-emerald-50 text-emerald-700' : 'bg-sky-50 text-[#071A52]'}`}><Icon size={19} /></span><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xl font-extrabold text-[#071A52]">{value}</p></div></div></div>; }
function Field({ label, value, onChange, type = 'text', min, placeholder, required }) { return <div><label className="mb-2 block text-sm font-bold text-slate-700">{label}</label><input type={type} min={min} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} required={required} className={inputClass} /></div>; }
function ModalActions({ onClose, label }) { return <div className="flex flex-col-reverse gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="rounded-2xl border border-slate-200 px-5 py-3 text-sm font-bold text-slate-600">Cancel</button><button type="submit" className="rounded-2xl bg-[#071A52] px-5 py-3 text-sm font-bold text-white">{label}</button></div>; }
function EmptyState({ search, onCreate }) { return <div className="mt-6 rounded-3xl border border-slate-200 bg-white p-10 text-center shadow-sm"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-sky-50 text-[#071A52]"><Search size={28} /></div><h2 className="mt-5 text-xl font-extrabold text-[#071A52]">{search ? 'No classes found' : 'No classes yet'}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{search ? 'Try another level, arm or form master.' : 'Create your first class and add its arm.'}</p>{!search && <button type="button" onClick={onCreate} className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-[#071A52] px-5 py-3 font-bold text-white"><Plus size={18} /> Create class</button>}</div>; }
const inputClass = 'w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-cyan-500 focus:ring-4 focus:ring-cyan-500/10';
function loadClasses() { try { const saved = localStorage.getItem(storageKey); return saved ? JSON.parse(saved) : starterClasses; } catch { return starterClasses; } }
